/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'farm-green': {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        'earth-brown': {
          50: '#fdf8f6',
          100: '#f2e8e5',
          200: '#eaddd7',
          300: '#e0cdc2',
          400: '#d2bab0',
          500: '#bfa094',
          600: '#a18072',
          700: '#977669',
          800: '#846358',
          900: '#43302b',
        },
        // AgriSmart Core Design System Tokens
        primary: '#2e7d32',
        'on-primary': '#ffffff',
        'primary-container': '#dcfce7',
        'on-primary-container': '#1b5e20',
        'inverse-primary': '#86efac',
        secondary: '#16a34a',
        'on-secondary': '#ffffff',
        'secondary-container': '#bbf7d0',
        'on-secondary-container': '#14532d',
        tertiary: '#45300d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5e4622',
        'on-tertiary-container': '#d6b587',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        surface: '#f9f9f9',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#424841',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        outline: '#727970',
        'outline-variant': '#c2c8be',
        'surface-tint': '#436746',
        'surface-variant': '#e2e2e2',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'primary-fixed': '#c4edc3',
        'primary-fixed-dim': '#a9d1a8',
        'on-primary-fixed': '#002108',
        'on-primary-fixed-variant': '#2b4e30',
        'secondary-fixed': '#94f990',
        'secondary-fixed-dim': '#78dc77',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005313',
        'tertiary-fixed': '#ffddb1',
        'tertiary-fixed-dim': '#e3c193',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#5a431f',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'display': ['Poppins', 'system-ui', 'sans-serif'],
      },
      animation: {
        'bounce-slow': 'bounce 2s infinite',
        'pulse-slow': 'pulse 3s infinite',
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.6s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px #22c55e' },
          '100%': { boxShadow: '0 0 20px #22c55e, 0 0 30px #22c55e' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        }
      }
    },
  },
  plugins: [],
}